---
title: "Final Project"
author: "Seth"
date: "2023-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars, echo=FALSE}

library(dplyr)
library(ggplot2)
library(readr)
crime <- read_delim("crime.csv", delim = "\t", 
    escape_double = FALSE, trim_ws = TRUE)
```

## Code



```{r crime, echo=FALSE}

crime <- crime %>% filter(grepl("2023", occ_date))
crime$zip_code <- factor(crime$zip_code)
crime$council_district <- factor(crime$council_district)
crime <- crime %>%
  mutate(across(c(rep_date, clearance_date), as.Date)) %>%  # Convert columns to Date objects
  mutate(clearance_time = clearance_date - rep_date)          # Calculate time difference

crime <- crime %>%
  mutate(sector = recode(sector, "ADAM" = "AD", "DAVID" = "DA", "DAVD" = "DA", "EDWARD" = "ED", "H" = "HE"))

crime <- crime %>%
  mutate(district = recode(district, "88" = "8")) %>%
  filter(!is.na(as.numeric(district)))
```

## Plots


```{r plots}
crime %>% filter(!is.na(council_district)) %>% mutate(family_violence = tolower(family_violence)) %>%
  ggplot(aes(x = council_district , y = family_violence, color = family_violence)) +
  geom_bar(stat = "identity", aes(fill = family_violence)) +
  labs(x = "Council District", y = "Number of Crime Reports") +
  ggtitle("Proportion of Family Violence Related Crimes Within Austin by Council District") +
  theme_minimal() 

crime %>% filter(!is.na(council_district) & longitude < -50) %>% 
  ggplot(aes(x = longitude, y = latitude, color = council_district)) +
  geom_point(size = 0.1) +
  labs(x = "Longitude", y = "Latitude") +
  ggtitle("Austin Crimes by Council District") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_minimal()


crime %>% filter(latitude > 25 & (clearance_status != "")) %>% 
  ggplot(aes(x = longitude, y = latitude, color = clearance_status)) +
  geom_point(size = 0.1) +
  labs(x = "Longitude", y = "Latitude") +
  ggtitle("Austin Crime Clearance Status by Location") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_minimal()


crime %>% filter(!is.na(council_district) & !(clearance_status == "N")) %>% 
  ggplot(aes(x = council_district, y = clearance_time)) +
  geom_bar(stat = "summary", fun = "mean", fill = "skyblue") +
  labs(title = "Average Clearance Time per Council District",
       x = "APD District",
       y = "Average Clearance Time (days)") +
  theme_minimal()

crime %>% filter(!is.na(council_district) & !is.na(clearance_status)) %>%
  ggplot(aes(x = council_district, fill = clearance_status)) +
  geom_bar(position = "fill") +
  labs(title = "Proportion of Uncleared Cases per Council District",
       x = "Council District",
       y = "Proportion",
       fill = "Clearance Status") +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  scale_fill_manual(values = c("skyblue", "darkorange", "lightgreen"), labels = c("Cleared by Arrest", "Not Cleared", "Cleared by Exception")) +
  theme_minimal()
```


